//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrocodileScore
    {
        public int Id { get; set; }
        public string PlayerName { get; set; }
        public double BlueScore { get; set; }
        public double GreenScore { get; set; }
        public double RedScore { get; set; }
        public double OrangeScore { get; set; }
        public double FrogScore { get; set; }
    }
}
