//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConexion
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AplicadaDBEntities : DbContext
    {
        public AplicadaDBEntities()
            : base("name=AplicadaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GravilotaScore> GravilotaScores { get; set; }
        public virtual DbSet<PianoHeroScore> PianoHeroScores { get; set; }
        public virtual DbSet<EsenciaScore> EsenciaScores { get; set; }
        public virtual DbSet<NinjaRunnerScore> NinjaRunnerScores { get; set; }
        public virtual DbSet<FlappyScore> FlappyScores { get; set; }
        public virtual DbSet<BananaScore> BananaScores { get; set; }
        public virtual DbSet<CrocodileScore> CrocodileScores { get; set; }
        public virtual DbSet<ExplorationScore> ExplorationScores { get; set; }
        public virtual DbSet<HunterScore> HunterScores { get; set; }
    }
}
